### PR TITLE
Update CICD for PyPI release

### PR DESCRIPTION
**Pull request by CBroz1**
Sorry - this should have been in the previous PR. I failed to check if the `.github` dir had been updated with the most recent versions

### CODE REVIEW

**Review by kabilar — CHANGES_REQUESTED** [review]
Thanks @CBroz1.  Looking at [element-calcium-imaging](https://github.com/datajoint/element-array-ephys/tree/main/.github), it doesn't seem that some of these files are required.

**Comment by CBroz1** [comment]
> Thanks @CBroz1. Looking at [element-calcium-imaging](https://github.com/datajoint/element-array-ephys/tree/main/.github), it doesn't seem that some of these files are required.

Does element-calcium-imaging PyPI publish with a tag? I think what you lined to is the old version

The reason I noticed in this case was because I pushed a tag and it didn't trigger the gh-action

**Comment by kabilar** [comment]
@CBroz1 Oops, I linked to `element-array-ephys`, but it also has the fewer files.  Not sure what is the latest.  But yes, we pushed a tag today to element-calcium-imaging and it triggered a pypi release.  If you pushed a tag today, it won't trigger the GHActions because there is already a release.

**Comment by CBroz1** [comment]
Ok - just pushed a commit to remove the shell scripts and the staging dir

**Comment by kabilar** [comment]
Thanks @CBroz1.  Will we also need the `development.yaml` file?

**Comment by kushalbakshi** [comment]
The `element-calcium-imaging` GHActions has a `development.yaml` file. I think it's necessary to trigger GHActions, but it doesn't need to be changed in any way. You can just add it to the `workflows` directory

**Comment by kabilar** [comment]
Just confirmed with Drew that we do not need the `development.yaml` file.

**Review by kabilar — APPROVED** [review]

**Comment by kabilar** [comment]
@CBroz1 Please tag and push the tag to upstream to trigger a release.  Thank you.

**Comment by CBroz1** [comment]
Hi @kabilar - I just discussed with Raphael who stressed the need for the `.staging` directory and `.sh` files. We'll need to re-add with the next PR

**Pull request merged**
